steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/visdet-mlflow-docker/mlflow-server:latest"
      - "."
    dir: "infra/docker/mlflow-server"
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/visdet-mlflow-docker/mlflow-server:latest"
timeout: 600s
